# Generated by Django 2.1.4 on 2019-01-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxtemp',
            name='region',
            field=models.CharField(default='UK', max_length=20),
            preserve_default=False,
        ),
    ]
